# Generated by Django 6.0.2 on 2026-02-04 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('best_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('first_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_results',
                'ordering': ['-last_attempt_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(help_text='The submitted SQL query')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, help_text='Query execution result', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.JSONField(blank=True, default=dict, help_text='Detailed feedback about the submission')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
