# Generated by Django 5.0.1 on 2026-02-04 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_initial'),
        ('courses', '0003_lesson'),
        ('submissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='submission',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='userresult',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='courses.lesson'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='assignments.assignment'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', 'lesson'], name='submissions_student_707a68_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['lesson', 'is_correct'], name='submissions_lesson__b7afa1_idx'),
        ),
        migrations.AddIndex(
            model_name='userresult',
            index=models.Index(fields=['student', 'assignment'], name='user_result_student_ca5096_idx'),
        ),
        migrations.AddIndex(
            model_name='userresult',
            index=models.Index(fields=['student', 'lesson'], name='user_result_student_987287_idx'),
        ),
    ]
