# Generated by Django 6.0.2 on 2026-02-09 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_module'),
        ('courses', '0007_attachment_module_lesson_module'),
        ('submissions', '0003_alter_userresult_unique_together_submission_lesson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userresult',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment__isnull', False)), fields=('student', 'assignment'), name='unique_student_assignment'),
        ),
        migrations.AddConstraint(
            model_name='userresult',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('student', 'lesson'), name='unique_student_lesson'),
        ),
    ]
