# Generated by Django 6.0.2 on 2026-02-14 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_module'),
        ('courses', '0008_attachment_module_and_more'),
        ('submissions', '0005_userresult_unique_student_assignment_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submissions_status_dcc854_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['student', '-submitted_at'], name='submissions_student_02388e_idx'),
        ),
    ]
