# Generated by Django 5.0.1 on 2026-02-04 19:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description shown on card')),
                ('lesson_type', models.CharField(choices=[('theory', 'Theory'), ('practice', 'Practice'), ('mixed', 'Theory & Practice')], default='mixed', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('theory_content', models.TextField(blank=True, help_text='Markdown supported')),
                ('practice_description', models.TextField(blank=True, help_text='Task description')),
                ('practice_initial_code', models.TextField(blank=True, help_text='Initial code template')),
                ('expected_query', models.TextField(blank=True, help_text='Expected SQL query')),
                ('expected_result', models.JSONField(blank=True, null=True)),
                ('required_keywords', models.JSONField(blank=True, default=list)),
                ('forbidden_keywords', models.JSONField(blank=True, default=list)),
                ('order_matters', models.BooleanField(default=False)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('time_limit_seconds', models.PositiveIntegerField(default=60)),
                ('max_attempts', models.PositiveIntegerField(blank=True, null=True)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.dataset')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order', 'created_at'],
                'unique_together': {('course', 'order')},
            },
        ),
    ]
