# Generated by Django 6.0.2 on 2026-02-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='database_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('sqlite', 'SQLite'), ('mariadb', 'MariaDB'), ('mongodb', 'MongoDB'), ('redis', 'Redis')], default='postgresql', max_length=20),
        ),
    ]
