# Generated by Django 6.0.2 on 2026-02-04 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for the student')),
                ('query_type', models.CharField(choices=[('select', 'SELECT'), ('insert', 'INSERT'), ('update', 'UPDATE'), ('delete', 'DELETE'), ('ddl', 'DDL'), ('nosql', 'NoSQL')], default='select', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('expected_query', models.TextField(help_text='The correct SQL query')),
                ('expected_result', models.JSONField(blank=True, help_text='Expected query result for comparison', null=True)),
                ('required_keywords', models.JSONField(blank=True, default=list, help_text='Keywords that must be present in the query (e.g., ["JOIN", "GROUP BY"])')),
                ('forbidden_keywords', models.JSONField(blank=True, default=list, help_text='Keywords that must not be present in the query')),
                ('order_matters', models.BooleanField(default=False, help_text='Whether row order matters in result comparison')),
                ('partial_match', models.BooleanField(default=False, help_text='Allow partial column matches')),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('time_limit_seconds', models.PositiveIntegerField(default=30, help_text='Maximum execution time for the query')),
                ('max_attempts', models.PositiveIntegerField(blank=True, help_text='Maximum number of submission attempts (null = unlimited)', null=True)),
                ('hints', models.JSONField(blank=True, default=list, help_text='Hints to show after failed attempts')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
