# Generated by Django 6.0.2 on 2026-02-05 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('database_type', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('ready', 'Ready'), ('busy', 'Busy'), ('error', 'Error'), ('stopping', 'Stopping'), ('stopped', 'Stopped')], default='creating', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('dataset_id', models.UUIDField(blank=True, null=True)),
                ('executions_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sandbox_containers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('submission_id', models.UUIDField(blank=True, null=True)),
                ('query', models.TextField()),
                ('execution_time_ms', models.PositiveIntegerField()),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='sandbox.sandboxcontainer')),
            ],
            options={
                'db_table': 'sandbox_execution_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
