# Generated by Django 6.0.2 on 2026-02-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='database_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='was_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='sandbox.sandboxcontainer'),
        ),
        migrations.AlterField(
            model_name='executionlog',
            name='execution_time_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['was_blocked', '-created_at'], name='sandbox_exe_was_blo_dd9a12_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['user_id', '-created_at'], name='sandbox_exe_user_id_06da09_idx'),
        ),
    ]
